name = "quinipro"
main = "dist/_worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[observability.logs]
enabled = true
invocation_logs = true

[assets]
directory = "dist"
